-- App identity is managed in Supabase Auth (`auth.users`) only.
-- Seed an admin with: `cd backend && npm run seed:admin`
--
-- Business tables (products, orders, seller profiles, etc.) reference `auth.users(id)` via UUID FKs.
